### ISSUE TITLE
NA purity

### ISSUE THREAD

**Issue by WangKang-Leo** [IARCbioinfo/facets-nf#3]
Thanks for your very helpful pipeline. I am just wondering why there are some NA values in purity (their ploidy are 2)...Here is my code:
```
nextflow run /home/kangwang/facets-nf/facets-nf/main.nf -profile singularity\
 --cohort_dir "/home/kangwang/facets-nf/data/Baseline" \
 --tn_file "/home/kangwang/facets-nf/data/TN_baseline.txt" \
 -with-singularity /home/kangwang/facets-nf/facets-suite_IARC.img --ref hg38  \
 --dbsnp_vcf_ref /home/kangwang/facets-nf/ref/00-common_all.vcf.gz \
 --analysis_type exome \
 --suffix_tumor "" --suffix_normal "" \
 -resume
```

Can I refine it by changing some parameters?

**Comment by nalcala** [comment]
Hi WangKang-Leo,

Sorry for the late response. As this is a facet problem and directly a problem with the workflow, I encourage you to see the facets documentation and ask the devs for support for a final answer, but what I think is happening is that when no copy number is detected by facets (all segments are diploid), facets cannot estimate purity, hence the output of NA. It is not a bug but a methodological limitation. From our experience, it happens either in very quiet tumors with very few chromosomal rearrangements (you can check this with a structural variant caller), or in very low purity samples. One thing that might help is to play with the cval value, which determines the degree of segmentation, to maybe allow the program to find smaller segments that would allow it to determine purity, although this comes at the expense of higher false positives I imagine so you should take the results with a grain of salt if you observe only few segments.

Hoping this is useful.

Cheers,

Nicolas
